### =========================================================================
### TESTS CRUD ANIMAL - PET FOSTER CONNECT
### =========================================================================

@baseUrl = http://localhost:3001
@animalId = 13 
## modofier l'id manuellement selon l'id en DB car le seed recrée à chaquoi fois des nouveaux id.
### 🔍 HEALTH CHECK
# Vérifie si l'API est lancée ET si la connexion à PostgreSQL fonctionne.
GET {{baseUrl}}/health

###

### 1. RÉCUPÉRER TOUS LES ANIMAUX
GET {{baseUrl}}/animals
Accept: application/json

###

### 2. CRÉER UN NOUVEL ANIMAL (LUNA LE CHAT)
# species_id: 2 pour Chat (selon tes vérifications DBeaver)
POST {{baseUrl}}/animals
Content-Type: application/json

{
  "name": "Luna",
  "species_id": 8,
  "sex": "female",
  "breed": "Siamois",
  "birth_date": "2023-01-16T00:00:00Z",
  "weight": 4.2,
  "description": "Une petite chatte très calme et propre.",
  "is_available": true
}

###

### 3. RÉCUPÉRER UN ANIMAL PRÉCIS (PAR SON ID)
GET {{baseUrl}}/animals/{{animalId}}
Accept: application/json

###

### 4. MODIFIER UN ANIMAL (PATCH)
# On change le poids et on peut changer le nom
PATCH {{baseUrl}}/animals/{{animalId}}
Content-Type: application/json

{
  "weight": 14.22,
  "name": "Boby le Grand"
}

###

### 5. TEST DE VALIDATION (DOIT ÉCHOUER - 400 BAD REQUEST)
# Le sexe "alien" n'existe pas dans l'Enum
POST {{baseUrl}}/animals
Content-Type: application/json

{
  "name": "Petit Gris",
  "sex": "ALIEN",
  "species_id": 1,
  "breed": "Inconnu",
  "birth_date": "2024-01-01T00:00:00Z",
  "weight": 5.0,
  "is_available": true
}

###

### 6. TEST DE VALIDATION (DOIT ÉCHOUER - 400 BAD REQUEST)
# Ici, le champ obligatoire "name" est absent
POST {{baseUrl}}/animals
Content-Type: application/json

{
  "sex": "MALE",
  "species_id": 1,
  "breed": "Inconnu",
  "birth_date": "2024-01-01T00:00:00Z",
  "weight": 5.0,
  "is_available": true
}

###

### 7. SUPPRIMER UN ANIMAL
DELETE {{baseUrl}}/animals/{{animalId}}